/**
 * API de Rapprochement Bancaire et Détection de Fraude
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShapContribution {
    feature: string;
    value: number;
    direction: 'positive' | 'negative';
}

export interface Explainability {
    summary?: string;
    factors?: Array<string>;
    shap_contributions?: Array<ShapContribution>;
}