/**
 * API de Rapprochement Bancaire et Détection de Fraude
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Explainability } from './explainability';


export interface TransactionOutput { 
    tenant_id: string;
    transaction_reference: string;
    id: string;
    date: string;
    description: string;
    amount: number;
    /**
     * Flag indiquant si la transaction est suspecte
     */
    isFraud?: boolean;
    /**
     * Probabilité de fraude (de 0.0 à 1.0)
     */
    fraudProbability?: number;
    /**
     * Statut du rapprochement bancaire
     */
    reconciliationStatus?: TransactionOutput.ReconciliationStatusEnum;
    explainability?: Explainability;
}
export namespace TransactionOutput {
    export const ReconciliationStatusEnum = {
        Matched: 'MATCHED',
        Unmatched: 'UNMATCHED',
        Suspicious: 'SUSPICIOUS'
    } as const;
    export type ReconciliationStatusEnum = typeof ReconciliationStatusEnum[keyof typeof ReconciliationStatusEnum];
}


