[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -ra
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
env =
    ENABLE_TEST_TOKEN_ENDPOINT=true
