global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fraud-detection"
    metrics_path: /metrics
    static_configs:
      - targets: ["fraud-service:8005"]

  - job_name: "multi-banking"
    metrics_path: /metrics
    static_configs:
      - targets: ["multi-banking:8010"]

  # Neo4j metrics require Neo4j Prometheus exporter
  # - job_name: "neo4j"
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ["neo4j_db:7474"]