/**
 * API de Rapprochement Bancaire et Détection de Fraude
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransactionInput { 
    tenant_id: string;
    mongo_transaction_id: string;
    id: string;
    date: string;
    description: string;
    amount: number;
    sender_balance_before: number;
    sender_balance_after: number;
    receiver_balance_before: number;
    receiver_balance_after: number;
    /**
     * Type de transaction (TRANSFER, CASH_OUT, PAYMENT, etc.)
     */
    transaction_type: string;
}

