events {}

http {

    upstream multi_banking {
        server multi-banking:8010;
    }

    upstream fraud_service {
        server fraud-service:8005;
    }

    server {
        listen 80;

        location /banking/ {
            proxy_pass http://multi_banking/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /fraud/ {
            proxy_pass http://fraud_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}